apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: jfrog-integration
spec:
  selector:
    app: nginx-reverse-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  